### ISSUE TITLE
Error when fetching pkg's during build

### ISSUE THREAD

**Issue by joehoeller** [Hulkmaster/advanced-vue-guide#1]
Error:

```
error An unexpected error occurred: "https://registry.yarnpkg.com/event-stream/-/event-stream-3.3.6.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/usr/front/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by joehoeller** [comment]
UPDATE:

I changed the url to:
`https://registry.yarnpkg.com/event-stream/-/event-stream-3.3.6.tgz`
on line 2082 in the` ./front/yarn.lock file`.

**Comment by Hulkmaster** [comment]
Hi!

Thanks for reporting.

Usually its bad idea to manually touch .lock file, because it was never meant for manual touching :)

In that case problem was, that lockfile was generated pretty long ago, so, basically, you could just remove .lock file, do `yarn` again, it would fetch new urls, and everything would fine :)

but i decided to update packages, fix couple minor issues, and update guide on medium according to these changes :)
